version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-quiz-app
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}
      # Option 1: Use mounted JSON file (recommended)
      - GOOGLE_SERVICE_ACCOUNT_FILE=/app/google-credentials.json
      # Option 2: Pass JSON as environment variable
      # - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
      # Option 3: Individual variables (backward compatibility)
      # - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      # - GOOGLE_PRIVATE_KEY_ID=${GOOGLE_PRIVATE_KEY_ID}
      # - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      # - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_CERT_URL=${GOOGLE_CLIENT_CERT_URL}
    volumes:
      # Mount the credentials file (if using file-based approach)
      - ./google-credentials.json:/app/google-credentials.json:ro
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: telegram-quiz-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge