version: '3.8'

services:
  bot:
    build: .
    container_name: tgquizprizebot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - quiz-network
    depends_on:
      - api

  api:
    image: telegram-quiz-app:latest
    container_name: quiz-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - quiz-network
    volumes:
      - ../google-credentials.json:/app/google-credentials.json:ro

networks:
  quiz-network:
    driver: bridge
